---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
secretGenerator:
  - name: weave-admin-password
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
