apiVersion: v1
kind: Secret
metadata:
    name: weave-admin-password
    namespace: flux-system
stringData:
    passwordHash: ENC[AES256_GCM,data:ij0LfQ8sfXvdOy/73Ipt+qU5uJbjYSIYqCgxReIX1ncff/wPpKrvzQbkEv1Uuhj6YV+jCWmMluy474KB,iv:wwdh639MdCHhq7xJcrRtjo2eAspaF78O9JW9Nr4b87g=,tag:8/xXzAB3kLjZomAO+ri1XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sw66dv4ns66xaarwhwk9rfx75qturah93ze28nx3v9qz24vx2qmsewu6v4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdEJlK0lYWE51YmtlUDUr
            SFRSVUNaRTBHNnd1azFkTFNzVGV5REN3MnpRCndTa2ZNcjMvWXcxV2lQdGZ4WjRt
            MXlKKzQxaExZRDkrNG5MeG9obzQzTzgKLS0tIGNJdDdBM2FnN0U0dkFLbTd1THBv
            NEg0SXNIeEp5V3A0M21hZE5ETDB1WTAKBjXjbNrQIb69idtlVepCQj81rHSVK3kA
            59pRalznHXJUv5cvaIkWzYE2CBp6TU07i1sbzw+TRainiaJRVS5zUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T09:40:25Z"
    mac: ENC[AES256_GCM,data:/uRj6qel8tQggPFYLZ1nh/iC1zZFHvt1D0pdJBvb2496iSaUmdvsdKltpdB6sRz0/YVsawuHnH0KB9MG/398osir4EFOXUX42pO8cvZW3hE9zpOk5Ae+tnqEPvERlT3eyTHn3cPHukFQqjrZSl79i6ouKjR932omw6G7haQ9XEY=,iv:Y1WAN3hAx2eES26zsLC1sqsEKSlXoRZpVEqh5RQ7FT0=,tag:24SaeAA25bZVFV2u2mzTyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
