apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:y7tHuwUjCI+lf83napoQQkVTT0fdCvkeaK2J3fXBG89FkImC3+pC2fSpi7lHXofAxhMKhsD9RoBdQhdnH0c+LQyod6E2QO0c1+IZ6BlOb7PArP6bKVrugika52XIuA==,iv:3UHF7paNZO313y5kykc0T6TYDu4u046JIgfhvRraFwg=,tag:oCgjHmJLUQJEsuaG/BloRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sw66dv4ns66xaarwhwk9rfx75qturah93ze28nx3v9qz24vx2qmsewu6v4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVmNrWlBrMkE3VEN2VDQx
            V05ZamFkc3VwRzMySmhJdEVHc09EcWNyOWk0CmJnK1ROUWdsOTl0T1h6WlhPZ0Vm
            aUh5dkNMejBzSUJIMHNYOWxoSzErYTQKLS0tIEsrY2tpMmhuOFM3ejBneGZ0amdZ
            ZWNLOGVXNGkvcWp3STErcmRqQnpMU0kK3sQ4vwNQShdCBYIkVeehdrtJzKgTP1wF
            9x52DLBqwu8tDhRa27bi6QpIn+gjKmsu1M8rVMqQzrPbTohkLmsqJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-20T11:57:03Z"
    mac: ENC[AES256_GCM,data:pwxtGjs8r2ixHxf0tb9Pcrm76pjMcqLsynSXY21tzDnn6T/X//KwOhUOE8FU4P+wHs2EotvLqhIOpHILNnqXYePMiCftsbhifx8HrzHF0dcxoXD5oorxHOpXHcRM6Cm9edYms/+bqZ75t5LvUVeyVCW34pyHrYvK564RIAhyGXY=,iv:LDBUpKK3NzmwIAOB++G26UbczCyfdQhRGQqtRnzu65Y=,tag:UHjoCiD6rIP/SlecLf24LQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
