apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:BINLF2QX/fvj7eHRANMVp66cL5GWqTevuTFlubswSWvNsWJN95kQ1hPdQPQTaScs6sIpUve3VipAVZz2YvuX0JkNeqVOqSPNUd9sdIFO2d48VK+CjZlJ/r2qrJe1cw==,iv:F7YUQu418A/0WeG/nZjyrX8Ci/riI88EvRd4B2SwYK0=,tag:+RGOUZqogPh8CcwyEi17Aw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:OAoDj5E5nkYd,iv:mq+QT7dePOKGhN5JNOMkiJqO3qy5Us8sONhvAeye90g=,tag:xx+dyNHxb+j279rOATmLQA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:OJxmyahzAkhrcmXMoYS06g==,iv:4R4gGjZN6RRewgQYLr3b96Ab0uMgE9hovwtfJHqh66M=,tag:vPJR7foMVpes/hi4tcigOg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Tp3q0N8qKw5eAr5kkS2NP2CCXiSm9c3OpOtXX7AzWd6LOUBF,iv:hWuQkATAU34y+WXjLWbRHYJw5NEbtn21gUfMbhvMXOM=,tag:A2NwRr+mLAMltYIeFKfsGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sw66dv4ns66xaarwhwk9rfx75qturah93ze28nx3v9qz24vx2qmsewu6v4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WDNFcG5RUnpiUFBGVzlW
            Q0t0WFU0R2ZiQ0RiZkNTTFZPVzhVWjlDVFdNClZsQ3YzVEN3WHhoTTNScTFGRUhI
            S0pCVmFzb1VUTk9WTFo3MWZZTHYzdmsKLS0tIEZBTElKRmFqVU0vVDQ4OVR5T3dk
            ZXE1amJlMEZ0aTVMTmFZckhtTk9UWDQKyeVA0P9A+lxLAjdkMjkCToj2kIUQ7ArZ
            yoik5GmpMNXZY9novzaeO67bLM9G4XMnRwbfaWhDNDv5Kw57HWacLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-21T13:32:19Z"
    mac: ENC[AES256_GCM,data:554u//iEY5MpZteKasJywxgQsdC0vSTc/MpLCU1NMyd2fAjhKeGOgRSFQssw4oDW2A4eJc+z31uebstjXUiWkp6evdBH4kF4HIDoIg3jZMvTY7RnvA5zKzY+8ngryhOeLy11dfIQtRPIZ7lLfOC17vqHkJWrYKdBwISXqq/wbrY=,iv:RKRp8R4sia6KMnVLozOBvpP0JLUzB7AJVHqcDcfELog=,tag:XjvZIEq52qFVW/1PT7Zfsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
